name:                tlaplus
version:             0.1

license:             BSD3
license-file:        LICENSE

author:              Reto Kramer <kramer@acm.org>
maintainer:          kramer@acm.org
stability:           experimental
synopsis:            TLA+ AST, parser and pretty printer
category:            Language
description:
  Library to facilitate TLA+ processing in Haskell.
  For TLA+ information, please refer to http://www.lamport.org

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fno-warn-name-shadowing

default-extensions:
  - DeriveDataTypeable
  - FlexibleContexts
  - DeriveLift
  - TypeFamilies
  - TypeOperators
  - ScopedTypeVariables
  - RankNTypes

library:
  exposed-modules:
    - Language.TLAPlus.Syntax
    - Language.TLAPlus.Pretty
    - Language.TLAPlus.Parser
    - Language.TLAPlus.ParserState
    # exported for use in short's parser -- FIXME (use "other-modules:")

  dependencies:
    - base >= 4
    - syb
    - containers
    - wl-pprint
    - parsec >= 3.0.1
    - lens
    - template-haskell
    - mono-traversable
  source-dirs:    src
