
name: tlaplus-quickcheck

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fno-warn-name-shadowing

default-extensions:
  - TupleSections
  - TypeApplications
  - DeriveGeneric

library:
  source-dirs: src
  dependencies:
    - base
    - containers
    - dlist
    - lens
    - template-haskell
    - text
    - tlaplus
    - tlaplus-eval

tests:
  test1:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - base
      - containers
      - hspec
      - lens
      - parsec >= 3.0.1
      - template-haskell
      - text
      - tlaplus
      - tlaplus-eval
      - tlaplus-quickcheck
