
name: tlaplus-quickcheck

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fno-warn-name-shadowing

library:
  source-dirs: src
  dependencies:
    - base

tests:
  test1:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - base
      - tlaplus
      - parsec >= 3.0.1
      - hspec
      - lens
