
name: tlaplus-quickcheck

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fno-warn-name-shadowing

library:
  source-dirs: src
  dependencies:
    - base
    - template-haskell
    - tlaplus
    - lens

tests:
  test1:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - base
      - tlaplus
      - parsec >= 3.0.1
      - template-haskell
      - hspec
      - lens
      - tlaplus-quickcheck
