sudo: false

language: generic
cache:
  directories:
  - $HOME/.stack
  - "$TRAVIS_BUILD_DIR/.stack-work"

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack test --no-run-tests --only-dependencies

script:
  - stack test
